### PR TITLE
Updated CredentialClient to utilize ProviderResolver methods

### LINKED ISSUE #138: Cleanup: utilize ProviderResolver in CredentialClient
Centralize all the resolution and intent creation code into ProviderResolver, where it is easier to test.

### PR DESCRIPTION
**Pull request by nerdyverde**
Fixes #138

### CODE REVIEW

**Review by dxslly — APPROVED** [review]
LGTM. but based one the imports order (static imports should be listed first) it looks like our checkstyle was not enforced on this PR.  @iainmcgin any idea why that might be?

**Comment by iainmcgin** [comment]
Weird, it was likely a transient failure in the build hook that notifies travis of new PRs.

**Comment by iainmcgin** [comment]
I ran the checks locally (can't figure out how to re-trigger them on travis), it's just import order that needs to be fixed.

**Comment by nerdyverde** [comment]
I'm guessing that there are some settings that I need to configure on my end. Are there some settings files that we need to include in the repo?

**Review by StanKocken — APPROVED** [review]
LGTM

**Comment by nerdyverde** [comment]
Apparently new commits don't trigger the checks on Travis either. I've fixed the import order and confirmed it by running the checks locally. Any objections to merging?

**Comment by iainmcgin** [comment]
If the build breaks after the merge, please fix it :)

**Pull request merged**
